set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_ENV_PASSTHROUGH PATH)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)

# nscurl: target xp64
set(VCPKG_C_FLAGS "-static-libgcc -march=x86-64 -D_WIN32_WINNT=0x0502")
set(VCPKG_CXX_FLAGS ${VCPKG_C_FLAGS})
